CREATE TABLE "artist_band" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100),
  "genre" varchar(25)
);

CREATE TABLE "albums" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "genre" varchar(25),
  "price" NUMERIC(10,2) NOT NULL,
  "artist_band_id" Int
);

CREATE TABLE "songs" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50),
  "album_id" Int
);

CREATE TABLE "customers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100),
  "address" varchar(100),
  "username" varchar(20) UNIQUE NOT NULL,
  "password_hash" varchar(100) NOT NULL,
  "email_address" varchar(50) UNIQUE NOT NULL
);

CREATE TABLE "cart" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "customer_id" Int
);

CREATE TABLE "cart_items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cart_id" Int,
  "album_id" Int NOT NULL,
  "item_quantity" Int
);

CREATE TABLE "orders" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "customer_id" Int,
  "customer_name" varchar(100),
  "customer_address" varchar(100),
  "email_address" varchar(50),
  "date" timestamp,
  "status" text,
  "total" NUMERIC(10,2)
);

CREATE TABLE "order_items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" Int,
  "album_id" Int,
  "item_quantity" Int,
  "price" NUMERIC(10,2)
);

ALTER TABLE "albums" ADD FOREIGN KEY ("artist_band_id") REFERENCES "artist_band" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "songs" ADD FOREIGN KEY ("album_id") REFERENCES "albums" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cart_items" ADD FOREIGN KEY ("cart_id") REFERENCES "cart" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_items" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_items" ADD FOREIGN KEY ("album_id") REFERENCES "albums" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("customer_id") REFERENCES "customers" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cart" ADD FOREIGN KEY ("customer_id") REFERENCES "customers" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cart_items" ADD FOREIGN KEY ("album_id") REFERENCES "albums" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cart_items" ADD CONSTRAINT cart_items_cart_album_unique UNIQUE ("cart_id", "album_id");

ALTER TABLE "orders" ALTER COLUMN "date" SET DEFAULT NOW();

-- make sure active cart is unique to a customer , only one active cart per customer

ALTER TABLE "cart" ALTER COLUMN "customer_id" SET NOT NULL;

ALTER TABLE "cart" ADD CONSTRAINT cart_customer_unique UNIQUE ("customer_id");

ALTER TABLE cart_items ALTER COLUMN cart_id SET NOT NULL;

ALTER TABLE cart_items ALTER COLUMN item_quantity SET NOT NULL;

ALTER TABLE cart_items ADD CONSTRAINT cart_items_quantity_positive CHECK (item_quantity > 0);

-- every order must belong to a customer and have a total and valid status
ALTER TABLE orders ALTER COLUMN customer_id SET NOT NULL;
ALTER TABLE orders ALTER COLUMN total SET NOT NULL;
ALTER TABLE orders ALTER COLUMN status SET NOT NULL;
ALTER TABLE orders ADD CONSTRAINT orders_status_valid
  CHECK (status IN ('pending','paid','shipped','cancelled'));

-- every order_item must belong to an order and have an album, a positive quantity and a price
ALTER TABLE order_items ALTER COLUMN order_id SET NOT NULL;
ALTER TABLE order_items ALTER COLUMN album_id SET NOT NULL;
ALTER TABLE order_items ALTER COLUMN item_quantity SET NOT NULL;
ALTER TABLE order_items ALTER COLUMN price SET NOT NULL;
ALTER TABLE order_items ADD CONSTRAINT order_items_quantity_positive CHECK (item_quantity > 0);





-- ran the following in the terminal to :
--That UNIQUE constraint isn't just tidiness — it's what makes "add to cart" idempotent later.
-- With it, you can write a single INSERT ... ON CONFLICT (cart_id, album_id) DO UPDATE SET item_quantity = cart_items.item_quantity + EXCLUDED.item_quantity,
-- and adding the same album twice bumps the quantity instead of duplicating the row.
-- Without it you'd need a SELECT-then-branch, which has a race condition.
-- also ran the following in the terminal to make sure cart_items quantity can't be 0 or negative:
-- psql -d PhysicalCDStore \
--  -c 'ALTER TABLE cart_items ALTER COLUMN cart_id SET NOT NULL;' \
--  -c 'ALTER TABLE cart_items ALTER COLUMN item_quantity SET NOT NULL;' \
--  -c 'ALTER TABLE cart_items ADD CONSTRAINT cart_items_quantity_positive CHECK (item_quantity > 0);'

